name: Build

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    name: Package and Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # So git maven plugin finds all history there

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package  -DskipTests --file pom.xml

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: pom

      - name: Publish to Github Packages, hopefully
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn -B deploy  -DskipTests --file pom.xml

